blank_issues_enabled: true
contact_links:
  - name: Question or support
    url: https://github.com/asadhanif3188/mlops-platform-on-eks/discussions
    about: Please ask and answer questions here. See SUPPORT.md for guidance.
